---
title: "RWorksheet_Joven#4a.Rmd"
author: "Jowi Lorenz Nyl Joven BSIT 2-B"
date: "2023-11-22"
output: pdf_document
---

``` {r}
a_shoe_size <- c(6.5, 9, 8.5, 8.5, 10.5, 7, 9.5, 9, 13, 7.5, 10.5, 8.5, 12, 10.5)
a_shoe_size
a_height <- c(66, 68, 64.5, 65, 70, 64, 70, 71, 72, 64, 74.5, 67, 71, 71)
a_height
a_gender <- c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F", "M", "F", "M", "M")
a_gender

houseHold_data <- data.frame(a_shoe_size,a_height,a_gender)
houseHold_data
library(readr)
csv_file <-"HouseHoldData.csv"
write.csv(houseHold_data, file = csv_file)
houseHold_data <- read.csv("HouseHoldData.csv")
houseHold_data



df1 <- data.frame(a_shoe_size,a_height,a_gender)
print(df1)
b_shoe_size <- c(13, 11.5, 8.5, 5, 5, 10, 6.5, 7.5, 8.5, 10.5, 8.5, 11, 9, 13)
b_height <- c(77, 72, 59, 62, 72, 66, 64, 67, 73, 69, 72, 70, 69, 70)
b_gender <- c("M", "M", "F", "F", "M", "F", "F", "M", "M", "F", "M", "M", "M", "M")
df2 <- data.frame(b_shoe_size,b_height,b_gender)
print(df2)
combined_df <- cbind(df1,df2)
print(combined_df)
males_df1 <- subset(df1, a_gender == "M")
females_df1 <- subset(df1, a_gender == "F")
males_df2 <- subset(df2, b_gender == "M")
females_df2 <- subset(df2, b_gender == "F")
print("Males in df1:")
print(males_df1)
print("Females in df1:")
print(females_df1)
print("Males in df2:")
print(males_df2)
print("Females in df2:")
print(females_df2)


mean_shoe_size_df1 <- mean(df1$a_shoe_size)
mean_shoe_size_df1 
mean_height_df1 <- mean(df1$a_height)
mean_height_df1

mean_shoe_size_df2 <- mean(df2$b_shoe_size)
mean_shoe_size_df2
mean_height_df2 <- mean(df2$b_height)
mean_height_df2
```

```{r}
#2. 
months_vector <-c("March","April","January","November","January","September","October","September","November","August","January","November","November",
                  "February","May","August","July","December","August","August","September",
                  "November","February","April") 
months_vector 
```
```{r}
#3. 
factor_months_vector <- factor(months_vector) 
summary(factor_months_vector)
```

```{r}
#4. 
direction<-c("East","West","North")
direction
frequency <-c(1,4,3) 
frequency
df <- data.frame(Direction = direction, Frequency = frequency)
direction_frequency <- df
new_order_data <- factor(direction_frequency$Direction, levels = c("East", "West", "North"))
print(new_order_data)
```

```{r}
#5

```

```{r}
#6
generate_random_number <- function() {
  return(sample(1:50, 1))
}

user_input <- 20  # Predefined user input

if (user_input < 1 || user_input > 50) {
  print("The number selected is beyond the range of 1 to 50")
} else if (user_input == 20) {
  print("TRUE")
} else {
  print(user_input)
}

```


```{r}
#7
calculate_bills <- function(price) {
  if (price %% 50 != 0) {
    print("Price must be a multiple of 50.")
    return(NULL)
  }
  
  bills <- c(1000, 500, 200, 100, 50)
  bill_count <- 0
  
  for (bill in bills) {
    count <- price %/% bill
    if (count > 0) {
      bill_count <- bill_count + count
      price <- price %% bill
    }
  }
  
  print(paste("Minimum number of bills needed to purchase:", bill_count))
}

snacks <- c("Juice", "Bread", "Fried Chicken", "Baked Mac", "Carbonara", "Cake", "Lasagna")

# Setting selected_snack to 6 by default (corresponding to "Cake")
selected_snack <- 6
snack_prices <- c(50, 100, 150, 200, 250, 400, 350)

if (selected_snack >= 1 && selected_snack <= length(snacks)) {
  price <- snack_prices[selected_snack]
  calculate_bills(price)
} else {
  print("Invalid selection.")
}

```


```{r}
#8

name <- c("Annie", "Thea", "Steve", "Hanna")
name
grade1 <-c(85,65,75,95)
grade1
grade2 <-c(65,75,55,75)
grade2
grade3 <-c(85,90,80,100)
grade3
grade4 <-c (100,90,85,90)
grade4
df <- data.frame(Name = name, Grade1 = grade1, Grade2 = grade2, Grade3 = grade3, Grade4 = grade4)
Name_Grade <- df
print(Name_Grade)


#a
#    Name Grade1 Grade2 Grade3 Grade4
#1 Annie     85     65     85    100
#2  Thea     65     75     90     90
#3 Steve     75     55     80     85
#4 Hanna     95     75    100     90

#b
for (i in 1:nrow(df)) {
  avg <- (df[i, "Grade1"] + df[i, "Grade2"] + df[i, "Grade3"] + df[i, "Grade4"]) / 4
  formatted_output <- paste(df[i, "Name"], "'s average grade this semester is ", sprintf("%.2f", avg), ".", sep = "")
  print(formatted_output)
}
#[1] "Annie's average grade this semester is 83.75."
#[1] "Thea's average grade this semester is 80.00."
#[1] "Steve's average grade this semester is 73.75."
#[1] "Hanna's average grade this semester is 90.00."

#c
avg_grade1 <- sum(grade1) / length(grade1)
avg_grade2 <- sum(grade2) / length(grade2)
avg_grade3 <- sum(grade3) / length(grade3)
avg_grade4 <- sum(grade4) / length(grade4)

lowest_avg <- min(avg_grade1, avg_grade2, avg_grade3, avg_grade4)

if (lowest_avg == avg_grade1) {
  statement <- paste("The 1st test was difficult.")
  print(statement)
} else if (lowest_avg == avg_grade2) {
  statement <- paste("The 2nd test was difficult.")
  print(statement)
} else if (lowest_avg == avg_grade3) {
  statement <- paste("The 3rd test was difficult.")
  print(statement)
} else {
  statement <- paste("The 4th test was difficult.")
  print(statement)
}

#[1] "The 2nd test was difficult."

#d
for (i in 1:nrow(df)) {
  highest_grade <- max(df[i, "Grade1"], df[i, "Grade2"], df[i, "Grade3"], df[i, "Grade4"])
  if (highest_grade > 90) {
    statement <- paste(df[i, "Name"], "'s highest grade this semester is", highest_grade, ".")
    print(statement)
  }
}
#[1] "Annie 's highest grade this semester is 100 ."
#[1] "Hanna 's highest grade this semester is 100 .
#[1] "Hanna's average grade this semester is 90.0

```